[build]
  publish = "."

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/about.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/guide.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/privacy.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/terms.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/contact.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/sitemap.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/articles/*"
  [headers.values]
    Cache-Control = "no-cache"
